version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root

    db:
        image: mysql:8.1
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    redis:
        image: redis:alpine
        container_name: laravel_redis
        restart: always
        ports:
            - "6379:6379"
volumes:
    db_data:
